import { NgModule } from "@angular/core";
import { defineCustomElements } from "kickstand-ui/loader";

import {
    KsAccordion,
    KsAccordionSlide,
    KsAlert,
    KsBadge,
    KsBreadcrumbs,
    KsButton,
    KsButtonBar,
    KsCard,
    KsCardBody,
    KsCardFooter,
    KsCarousel,
    KsCarouselSlide,
    KsColumn,
    KsDropdown,
    KsDropdownItem,
    KsForm,
    KsFormField,
    KsGallery,
    KsIcon,
    KsImg,
    KsLoading,
    KsLoadingOverlay,
    KsMenuBar,
    KsMenuGroup,
    KsMenuItem,
    KsMenuRow,
    KsModal,
    KsModalFooter,
    KsOverlay,
    KsProgressBar,
    KsRadio,
    KsResponsiveEmbed,
    KsRow,
    KsScrollToTop,
    KsSideDrawer,
    KsSpinBox,
    KsSwitch,
    KsTab,
    KsTabs,
    KsTooltip
} from "./directives/proxies";

defineCustomElements(window);

const DECLARATIONS = [
    // proxies
    KsAccordion,
    KsAccordionSlide,
    KsAlert,
    KsBadge,
    KsBreadcrumbs,
    KsButton,
    KsButtonBar,
    KsCard,
    KsCardBody,
    KsCardFooter,
    KsCarousel,
    KsCarouselSlide,
    KsColumn,
    KsDropdown,
    KsDropdownItem,
    KsForm,
    KsFormField,
    KsGallery,
    KsIcon,
    KsImg,
    KsLoading,
    KsLoadingOverlay,
    KsMenuBar,
    KsMenuGroup,
    KsMenuItem,
    KsMenuRow,
    KsModal,
    KsModalFooter,
    KsOverlay,
    KsProgressBar,
    KsRadio,
    KsResponsiveEmbed,
    KsRow,
    KsScrollToTop,
    KsSideDrawer,
    KsSpinBox,
    KsSwitch,
    KsTab,
    KsTabs,
    KsTooltip
];

@NgModule({
    declarations: DECLARATIONS,
    exports: DECLARATIONS,
    imports: [],
    providers: []
})
export class ComponentLibraryModule { }