/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IBreadcrumbs,
} from './components/breadcrumbs/breadcrumbs';

export namespace Components {
  interface CAlert {
    /**
    * Animation to use when the alert is dismissed.
    */
    'cssClass': string;
    'header': string;
    'htmlId': string;
    'type': string;
  }
  interface CBadge {
    'cssClass': string;
    'hollow': boolean;
    'htmlId': string;
    'type': string;
  }
  interface CBreadcrumbs {
    'breadcrumbs': IBreadcrumbs[];
    'cssClass': string;
    'htmlId': string;
  }
  interface CButton {
    'cssClass': string;
    'hollow': boolean;
    'htmlId': string;
    'icon': string;
    'iconDirection': string;
    'linkUrl': string;
    'size': string;
    'type': string;
  }
  interface CImg {
    'alt': string;
    'cssClass': string;
    'htmlId': string;
    'lazy': boolean;
    'src': string;
    'threshold': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCAlertElement extends Components.CAlert, HTMLStencilElement {}
  var HTMLCAlertElement: {
    prototype: HTMLCAlertElement;
    new (): HTMLCAlertElement;
  };

  interface HTMLCBadgeElement extends Components.CBadge, HTMLStencilElement {}
  var HTMLCBadgeElement: {
    prototype: HTMLCBadgeElement;
    new (): HTMLCBadgeElement;
  };

  interface HTMLCBreadcrumbsElement extends Components.CBreadcrumbs, HTMLStencilElement {}
  var HTMLCBreadcrumbsElement: {
    prototype: HTMLCBreadcrumbsElement;
    new (): HTMLCBreadcrumbsElement;
  };

  interface HTMLCButtonElement extends Components.CButton, HTMLStencilElement {}
  var HTMLCButtonElement: {
    prototype: HTMLCButtonElement;
    new (): HTMLCButtonElement;
  };

  interface HTMLCImgElement extends Components.CImg, HTMLStencilElement {}
  var HTMLCImgElement: {
    prototype: HTMLCImgElement;
    new (): HTMLCImgElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'c-alert': HTMLCAlertElement;
    'c-badge': HTMLCBadgeElement;
    'c-breadcrumbs': HTMLCBreadcrumbsElement;
    'c-button': HTMLCButtonElement;
    'c-img': HTMLCImgElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CAlert extends JSXBase.HTMLAttributes<HTMLCAlertElement> {
    /**
    * Animation to use when the alert is dismissed.
    */
    'cssClass'?: string;
    'header'?: string;
    'htmlId'?: string;
    'type'?: string;
  }
  interface CBadge extends JSXBase.HTMLAttributes<HTMLCBadgeElement> {
    'cssClass'?: string;
    'hollow'?: boolean;
    'htmlId'?: string;
    'type'?: string;
  }
  interface CBreadcrumbs extends JSXBase.HTMLAttributes<HTMLCBreadcrumbsElement> {
    'breadcrumbs'?: IBreadcrumbs[];
    'cssClass'?: string;
    'htmlId'?: string;
  }
  interface CButton extends JSXBase.HTMLAttributes<HTMLCButtonElement> {
    'cssClass'?: string;
    'hollow'?: boolean;
    'htmlId'?: string;
    'icon'?: string;
    'iconDirection'?: string;
    'linkUrl'?: string;
    'size'?: string;
    'type'?: string;
  }
  interface CImg extends JSXBase.HTMLAttributes<HTMLCImgElement> {
    'alt'?: string;
    'cssClass'?: string;
    'htmlId'?: string;
    'lazy'?: boolean;
    'src'?: string;
    'threshold'?: number;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'c-alert': CAlert;
    'c-badge': CBadge;
    'c-breadcrumbs': CBreadcrumbs;
    'c-button': CButton;
    'c-img': CImg;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


